// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpedemiyorfgqusdngrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZWRlbWl5b3JmZ3F1c2RuZ3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTMyMjIsImV4cCI6MjA1OTM2OTIyMn0.axN-LNmRb7cOY6YjXV687km1yaDb0q7I7jqxo6G8sJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);